name: Build and deploy to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Check environment variables
              run: |
                  echo "API_KEY=$VITE_API_KEY"
                  echo "AUTH_DOMAIN=$VITE_AUTH_DOMAIN"
                  echo "PROJECT_ID=$VITE_PROJECT_ID"
                  echo "STORAGE_BUCKET=$VITE_STORAGE_BUCKET"
                  echo "MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID"
                  echo "APP_ID=$VITE_APP_ID"
                  echo "DATABASE_URL=$VITE_DATABASE_URL"
              env:
                  VITE_API_KEY: ${{secrets.VITE_API_KEY}}
                  VITE_AUTH_DOMAIN: ${{secrets.VITE_AUTH_DOMAIN}}
                  VITE_PROJECT_ID: ${{secrets.VITE_PROJECT_ID}}
                  VITE_STORAGE_BUCKET: ${{secrets.VITE_STORAGE_BUCKET}}
                  VITE_MESSAGING_SENDER_ID: ${{secrets.VITE_MESSAGING_SENDER_ID}}
                  VITE_APP_ID: ${{secrets.VITE_APP_ID}}
                  VITE_DATABASE_URL: ${{secrets.VITE_DATABASE_URL}}

            - name: Install and build
              run: |
                  npm install
                  npm run build
              env:
                  VITE_API_KEY: ${{secrets.VITE_API_KEY}}
                  VITE_AUTH_DOMAIN: ${{secrets.VITE_AUTH_DOMAIN}}
                  VITE_PROJECT_ID: ${{secrets.VITE_PROJECT_ID}}
                  VITE_STORAGE_BUCKET: ${{secrets.VITE_STORAGE_BUCKET}}
                  VITE_MESSAGING_SENDER_ID: ${{secrets.VITE_MESSAGING_SENDER_ID}}
                  VITE_APP_ID: ${{secrets.VITE_APP_ID}}
                  VITE_DATABASE_URL: ${{secrets.VITE_DATABASE_URL}}

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: gh-pages
                  folder: dist
